### ISSUE TITLE
Difference between hvac_mode and set_temperature

### ISSUE THREAD

**Issue by phdelodder** [zxdavb/evohome_cc#15]
I'm going through the code and detect that hvac_mode: uses [self._evo_device.mode["setpoint"]](https://github.com/zxdavb/evohome_cc/blob/84b3f6f7933d4dcd612169d5fa18409e3f567513/custom_components/evohome_cc/climate.py#L140) and target_temperature: uses [self._evo_device.setpoint](https://github.com/zxdavb/evohome_cc/blob/84b3f6f7933d4dcd612169d5fa18409e3f567513/custom_components/evohome_cc/climate.py#L182). In case of an open window the target remains at eg 18 but the state is off, although the set point according to evohome is set to 5°c. So I guess the target _tempature should also be using self._evo_device.mode["setpoint"]?

**Comment by zxdavb** [comment]
Actually, this is not straightforward...

One issue is trying to shoe-horn the evohome schema into HA. Then there is the difference between the scheduled setpoint, the override setpoint, and the actual/current setpoint.

I the code backing `self._evo_device.setpoint` is a bit unsatisfactory, too...

In any case, I don't think setpoint should be influenced by open_window mode.

I will have another look at it sometime in the future

**Comment by zxdavb** [comment]
@phdelodder Can you close this, or provide more feedback? If it is still an issue, I can have a look at it.
