### ISSUE TITLE
Manual preset change - changes back to None, before then updating a minute later to 'temporary'

### ISSUE THREAD

**Issue by iMiMx** [zxdavb/evohome_cc#16]
Version 0.5.20

If I make a manual Preset change to a heating zone - for example, None -> Temporary - the UI will flick back to 'None', the original state, before updating to the new state (Temporary) around a minute later.  I don't think this used to happen on earlier releases, such as 0.5.10, although I will roll-back to check.

Video demo attached:

https://www.dropbox.com/s/hvr6x9ag0y6gb1k/Screen%20Recording%202021-03-08%20at%2012.04.24.mov?dl=0

**Comment by zxdavb** [comment]
@iMiMx I believe this is fixed - please let me know if I am wrong.
