### ISSUE TITLE
hvac_mode remains off after window open detection has timed out. 

### ISSUE THREAD

**Issue by phdelodder** [zxdavb/evohome_cc#22]
hvac_mode remains off after window open detection has timed out. 

I have noticed that it could happen when an open window was detected, and after X min the state returns to normal but the 
entity isn't fully updated:

![image](https://user-images.githubusercontent.com/7259755/111605601-b7b86c00-87d6-11eb-919a-ddc67fba38f5.png)

If I would restart HA it is fixed, so there must be small glitch some where.

Here are the logs:

[Logs.zip](https://github.com/zxdavb/evohome_cc/files/6162915/Logs.zip)

I'm thinking it's related to https://github.com/zxdavb/evohome_cc/blob/b119afafc5e5ab33fa29a903cec39d80d71010d8/custom_components/evohome_cc/climate.py#L151

**Comment by zxdavb** [comment]
@phdelodder Can you close this, or provide more feedback? If it is still an issue, I can have a look at it.
