### ISSUE TITLE
OTB Water Temps need rounding

### ISSUE THREAD

**Issue by danrp-git** [zxdavb/evohome_cc#35]
Round temperatures reported by the OTB to 2 decimal places.

**Comment by zxdavb** [comment]
Hello, thanks for reporting this issue.

However I am afraid you're going to have to give me more information that you have.

**Comment by danrp-git** [comment]
I'm seeing temperatures reported for the boiler water temp and return temperatures that appear unrounded, as an example here is my current boiler water temp as returned by the sensor in Home Assistant, 58.59765625.

**Comment by zxdavb** [comment]
TL;DR: it seems reasonable to round to 0.005, is that OK?

-----------------------------------------------------

In the instance you mention,  your OTB sent a packet with a payload containing a temperature represented at `3A99` (and not `3A98`, nor `3A9A`).

Decoding this value as appropriately gives:
```
>>> _get_f8_8("3A", "99")
58.59765625
```

So the first thing to say is that `58.59765625` is the exact value reported by the OTB.

I note also, there is:
```
>>> _get_f8_8("3A", "98")
58.59375
>>> _get_f8_8("3A", "99")
58.59765625
>>> _get_f8_8("3A", "9A")
58.6015625
```

Generally, we might expect a precision of 1/200th of a C?
```
>>> int(_get_f8_8("3A", "98")*200)/200
58.59
>>> int(_get_f8_8("3A", "99")*200)/200
58.595
>>> int(_get_f8_8("3A", "9A")*200)/200
58.6
```
... but even the, you'll get artefacts every so often:
```
>>> int(_get_f8_8("00", "04")*200)/200
0.015
>>> int(_get_f8_8("00", "05")*200)/200
0.015
```

**Comment by zxdavb** [comment]
```python
    def _get_f8_8(msb, lsb) -> Optional[float]:
        """Convert 2 bytes (as strs) into an OpenTherm f8_8 (float) value."""
        if msb == lsb == "FF":
            return None
        return int(float(_get_s16(msb, lsb) / 256) * 200) / 200
```

**Comment by zxdavb** [comment]
Actually, this will cause some issues for any who are using Fahrenheit, but I guess all OpenTherm systems use Celsius.

**Comment by zxdavb** [comment]
Closing, as I have addressed this - please re-reopen if it is still an issue after the next release (>=0.12.x).
