### ISSUE TITLE
OTB Relative Modulation Level

### ISSUE THREAD

**Issue by danrp-git** [zxdavb/evohome_cc#36]
Hi

The relative_modulation_level sensor appears to be reporting its percentage incorrectly. Looking at the values reported the % appears to be incorrectly multiplied by 1000.

Examples include: 4,900%, 5,300% etc...

Thanks

**Comment by zxdavb** [comment]
Dan - it's out by a factor of 100 - so your 4,900% is 49% - I have fixed this, and it will be in the next update.

**Comment by zxdavb** [comment]
Will close this- please re-open if it still is an issue with the next release.
