### ISSUE TITLE
When the preset mode is away, heat_demand is ignored

### ISSUE THREAD

**Issue by phdelodder** [zxdavb/evohome_cc#6]
When the preset mode of the controller is set to away and a zone is showing heat demand because the temperature is lower then the setpoint, this isn't visible in the climate entity. 

The state of that entity(zone) should not be "auto" but should be "head", as there is heat demand. 
As for the state of the controller is also showing "heat_demand" > 0 , so the state should also reflect that
[home-assistant.log](https://github.com/zxdavb/evohome_cc/files/5871719/home-assistant.log)

**Comment by phdelodder** [comment]
I have to validate this with the latest code

**Comment by zxdavb** [comment]
@phdelodder Can you close this, or provide more feedback?
